const express = require('express');
const { pool } = require('../config/database');
const PDFDocument = require('pdfkit');

const router = express.Router();

// Generate PDF of accepted students for an owner
router.get('/owner/:ownerId/accepted-students-pdf', async (req, res) => {
  try {
    const ownerId = req.params.ownerId;

  // Get owner information
  const [ownerInfo] = await pool.execute(
      'SELECT name, organization_name FROM owner_users WHERE id = ?',
      [ownerId]
    );

    // Fetch accepted job applicants
  const [jobApplicants] = await pool.execute(`
      SELECT s.name, s.email, s.student_college_id, c.name AS college_name, 
             j.title AS job_title, ja.applied_at
      FROM job_applications ja
      JOIN jobs j ON ja.job_id = j.id
      JOIN approved_students s ON ja.student_id = s.id
      LEFT JOIN colleges c ON s.college_id = c.id
      WHERE j.owner_id = ? AND ja.status = 'accepted'
      ORDER BY s.name ASC
    `, [ownerId]);

    // Fetch accepted event registrations
  const [eventApplicants] = await pool.execute(`
      SELECT s.name, s.email, s.student_college_id, c.name AS college_name, 
             e.title AS event_title, ea.applied_at
      FROM event_applications ea
      JOIN events e ON ea.event_id = e.id
      JOIN approved_students s ON ea.student_id = s.id
      LEFT JOIN colleges c ON s.college_id = c.id
      WHERE e.owner_id = ? AND ea.status = 'accepted'
      ORDER BY s.name ASC
    `, [ownerId]);

    // Set response headers for PDF download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename=accepted_students_report.pdf');

    // Create PDF document
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    doc.pipe(res);

    // Add header
    doc.fontSize(20).text('Accepted Students Report', { align: 'center' });
    doc.moveDown();
    
    if (ownerInfo[0]) {
      doc.fontSize(14).text(`Organization: ${ownerInfo[0].organization_name}`);
      doc.text(`Generated by: ${ownerInfo[0].name}`);
      doc.text(`Generated on: ${new Date().toLocaleDateString()}`);
      doc.moveDown();
    }

    // Check if there are any accepted students
    if (jobApplicants.length === 0 && eventApplicants.length === 0) {
      doc.fontSize(14).text('No accepted students found.', { align: 'center' });
      doc.end();
      return;
    }

    // Job Applications Section
    if (jobApplicants.length > 0) {
      doc.fontSize(16).text('Accepted Job Applications:', { underline: true });
      doc.moveDown(0.5);
      
      jobApplicants.forEach((student, idx) => {
        doc.fontSize(12)
           .text(`${idx + 1}. Name: ${student.name}`)
           .text(`   Email: ${student.email}`)
           .text(`   Student ID: ${student.student_college_id}`)
           .text(`   College: ${student.college_name || 'N/A'}`)
           .text(`   Job: ${student.job_title}`)
           .text(`   Applied: ${new Date(student.applied_at).toLocaleDateString()}`)
           .moveDown(0.3);
      });
      doc.moveDown();
    }

    // Event Applications Section
    if (eventApplicants.length > 0) {
      doc.fontSize(16).text('Accepted Event Registrations:', { underline: true });
      doc.moveDown(0.5);
      
      eventApplicants.forEach((student, idx) => {
        doc.fontSize(12)
           .text(`${idx + 1}. Name: ${student.name}`)
           .text(`   Email: ${student.email}`)
           .text(`   Student ID: ${student.student_college_id}`)
           .text(`   College: ${student.college_name || 'N/A'}`)
           .text(`   Event: ${student.event_title}`)
           .text(`   Registered: ${new Date(student.applied_at).toLocaleDateString()}`)
           .moveDown(0.3);
      });
    }

    // Add summary at the end
    doc.moveDown();
    doc.fontSize(14).text('Summary:', { underline: true });
    doc.fontSize(12)
       .text(`Total Accepted Job Applications: ${jobApplicants.length}`)
       .text(`Total Accepted Event Registrations: ${eventApplicants.length}`)
       .text(`Total Accepted Students: ${jobApplicants.length + eventApplicants.length}`);

    doc.end();

  } catch (error) {
    console.error('Error generating PDF report:', error);
    res.status(500).json({ error: 'Failed to generate PDF report' });
  }
});

module.exports = router;

// Generate PDF of accepted students for a specific EVENT
router.get('/event/:eventId/accepted-students-pdf', async (req, res) => {
  try {
    const eventId = req.params.eventId;

    // Get event details with owner info
    const [eventInfo] = await pool.execute(`
      SELECT e.title, e.event_date, e.location, e.max_participants,
             o.name as owner_name, o.organization_name
      FROM events e
      JOIN owner_users o ON e.owner_id = o.id
      WHERE e.id = ?
    `, [eventId]);

    if (eventInfo.length === 0) {
      return res.status(404).json({ error: 'Event not found' });
    }

    // Fetch accepted event registrations for the specific event
    const [eventApplicants] = await pool.execute(`
      SELECT s.name, s.email, s.student_college_id, s.date_of_birth,
             c.name AS college_name, ea.applied_at, ea.message
      FROM event_applications ea
      JOIN approved_students s ON ea.student_id = s.id
      LEFT JOIN colleges c ON s.college_id = c.id
      WHERE ea.event_id = ? AND ea.status = 'accepted'
      ORDER BY s.name ASC
    `, [eventId]);

    // Set response headers for PDF download
    const filename = `accepted_students_${eventInfo[0].title.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=${filename}`);

    // Create PDF document
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    doc.pipe(res);

    // Header
    doc.fontSize(20).text('Event Registration Report', { align: 'center' });
    doc.moveDown();

    // Event Information
    const event = eventInfo[0];
    doc.fontSize(16).text('Event Details:', { underline: true });
    doc.fontSize(12)
       .text(`Event Name: ${event.title}`)
       .text(`Organization: ${event.organization_name}`)
       .text(`Event Date: ${new Date(event.event_date).toLocaleDateString()}`)
       .text(`Location: ${event.location || 'N/A'}`)
       .text(`Max Participants: ${event.max_participants || 'Unlimited'}`)
       .text(`Report Generated: ${new Date().toLocaleDateString()}`)
       .text(`Generated by: ${event.owner_name}`);
    
    doc.moveDown();

    // Check if there are accepted students
    if (eventApplicants.length === 0) {
      doc.fontSize(14).text('No accepted students found for this event.', { align: 'center' });
      doc.end();
      return;
    }

    // Accepted Students Section
    doc.fontSize(16).text('Accepted Students:', { underline: true });
    doc.moveDown(0.5);

    eventApplicants.forEach((student, idx) => {
      doc.fontSize(12)
         .text(`${idx + 1}. ${student.name}`, { continued: true })
         .text(` (${student.student_college_id})`, { align: 'right' })
         .text(`    Email: ${student.email}`)
         .text(`    College: ${student.college_name || 'N/A'}`)
         .text(`    Date of Birth: ${new Date(student.date_of_birth).toLocaleDateString()}`)
         .text(`    Registration Date: ${new Date(student.applied_at).toLocaleDateString()}`);
      
      if (student.message) {
        doc.text(`    Message: ${student.message}`);
      }
      
      doc.moveDown(0.4);
    });

    // Summary
    doc.moveDown();
    doc.fontSize(14).text('Summary:', { underline: true });
    doc.fontSize(12)
       .text(`Total Accepted Students: ${eventApplicants.length}`)
       .text(`Acceptance Rate: ${event.max_participants ? 
         `${eventApplicants.length}/${event.max_participants}` : 
         `${eventApplicants.length} students`}`);

    doc.end();

  } catch (error) {
    console.error('Error generating event PDF report:', error);
    res.status(500).json({ error: 'Failed to generate PDF report' });
  }
});

// Generate PDF of accepted students for a specific JOB
router.get('/job/:jobId/accepted-students-pdf', async (req, res) => {
  try {
    const jobId = req.params.jobId;

    // Get job details with owner info
    const [jobInfo] = await pool.execute(`
      SELECT j.title, j.description, j.location, j.salary_range, j.job_type,
             o.name as owner_name, o.organization_name
      FROM jobs j
      JOIN owner_users o ON j.owner_id = o.id
      WHERE j.id = ?
    `, [jobId]);

    if (jobInfo.length === 0) {
      return res.status(404).json({ error: 'Job not found' });
    }

    // Fetch accepted job applications for the specific job
    const [jobApplicants] = await pool.execute(`
      SELECT s.name, s.email, s.student_college_id, s.date_of_birth,
             c.name AS college_name, ja.applied_at, ja.cover_letter
      FROM job_applications ja
      JOIN approved_students s ON ja.student_id = s.id
      LEFT JOIN colleges c ON s.college_id = c.id
      WHERE ja.job_id = ? AND ja.status = 'accepted'
      ORDER BY s.name ASC
    `, [jobId]);

    // Set response headers for PDF download
    const filename = `accepted_applicants_${jobInfo[0].title.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=${filename}`);

    // Create PDF document
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    doc.pipe(res);

    // Header
    doc.fontSize(20).text('Job Application Report', { align: 'center' });
    doc.moveDown();

    // Job Information
    const job = jobInfo[0];
    doc.fontSize(16).text('Job Details:', { underline: true });
    doc.fontSize(12)
       .text(`Job Title: ${job.title}`)
       .text(`Organization: ${job.organization_name}`)
       .text(`Location: ${job.location || 'N/A'}`)
       .text(`Job Type: ${job.job_type}`)
       .text(`Salary Range: ${job.salary_range || 'Not specified'}`)
       .text(`Report Generated: ${new Date().toLocaleDateString()}`)
       .text(`Generated by: ${job.owner_name}`);
    
    doc.moveDown();

    // Check if there are accepted applicants
    if (jobApplicants.length === 0) {
      doc.fontSize(14).text('No accepted applicants found for this job.', { align: 'center' });
      doc.end();
      return;
    }

    // Accepted Applicants Section
    doc.fontSize(16).text('Accepted Applicants:', { underline: true });
    doc.moveDown(0.5);

    jobApplicants.forEach((student, idx) => {
      doc.fontSize(12)
         .text(`${idx + 1}. ${student.name}`, { continued: true })
         .text(` (${student.student_college_id})`, { align: 'right' })
         .text(`    Email: ${student.email}`)
         .text(`    College: ${student.college_name || 'N/A'}`)
         .text(`    Date of Birth: ${new Date(student.date_of_birth).toLocaleDateString()}`)
         .text(`    Application Date: ${new Date(student.applied_at).toLocaleDateString()}`);
      
      if (student.cover_letter) {
        doc.text(`    Cover Letter: ${student.cover_letter.substring(0, 200)}${student.cover_letter.length > 200 ? '...' : ''}`);
      }
      
      doc.moveDown(0.4);
    });

    // Summary
    doc.moveDown();
    doc.fontSize(14).text('Summary:', { underline: true });
    doc.fontSize(12).text(`Total Accepted Applicants: ${jobApplicants.length}`);

    doc.end();

  } catch (error) {
    console.error('Error generating job PDF report:', error);
    res.status(500).json({ error: 'Failed to generate PDF report' });
  }
});

module.exports = router;
